[package]
name = "gpu-detection"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[dependencies]
anyhow = "1.0"
nvml-wrapper = "0.10"
serde = "1.0"
log = "0.4.21"
thiserror = "1.0.58"
libloading = "0.8.3"
