name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
      - pre-rel-*
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: CI

    runs-on: windows-latest
  
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71.0
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - run: cargo tree --locked

      - run: cargo fmt --all -- --check

      - run: cargo clippy --all-targets --all-features --workspace -- -D warnings

      - run: cargo test --all-features --workspace

      - name: Release Build
        if: startsWith(github.ref, 'refs/tags/')
        run: cargo build --workspace --release

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: target/release/*.exe
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre-rel-v') }}
