name: Build Release

on:
  push:
    tags:
      - v*
      - pre-rel-*
env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: CI
    runs-on: ${{ matrix.os }}-latest
    if: startsWith(github.ref, 'refs/tags/')
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu
          - windows

    env:
      X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: c:/vcpkg/installed/x64-windows-static
      OPENSSL_STATIC: 1
      
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71.0
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - run: cargo tree --locked
      
      - name: Windows setup
        if: matrix.os == 'windows'
        run: |
          vcpkg install openssl:x64-windows-static
          vcpkg integrate install

      - name: Build
        run: cargo build --workspace --release

      - name: Move descriptor
        run: cp conf/ya-dummy-ai.json target/release/ya-dummy-ai.json

      - name: Pack
        id: pack
        shell: bash
        env:
          OS_NAME: ${{ matrix.os }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          bash .ci/pack-build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            releases/runtime-*
            releases/dummy-framework-*
          prerelease: ${{ startsWith(github.ref, 'refs/tags/pre-rel-v') }}
