name: Tests

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
      - pre-rel-*
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: CI
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows

    env:
      X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR: c:/vcpkg/installed/x64-windows-static
      OPENSSL_STATIC: 1

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71.0
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - run: cargo tree --locked
      - run: cargo fmt --all -- --check

      - name: Windows setup
        if: matrix.os == 'windows'
        run: |
          vcpkg install openssl:x64-windows-static
          vcpkg integrate install

      - run: cargo clippy --all-targets --all-features --workspace -- -D warnings
      - run: cargo test --all-features --workspace
