name: Tests

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
      - pre-rel-*
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
  rust_stable: 1.76.0

jobs:
  test:
    name: CI
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu
          - windows

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.rust_stable }}
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2

      - run: cargo tree --locked
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features --workspace -- -D warnings
      - run: cargo test --all-features --workspace
